/* eslint-disable */
// Auto-generated by apps/docs/scripts/generate-registry-metadata.mjs
// Do not edit manually.

export type GeneratedRegistryType = "primitive" | "signature"

export type GeneratedRegistryEntry = {
  name: string
  type: GeneratedRegistryType
  title: string
  description: string
  docsPath: string
  importPath: string
  install: {
    package: string
    registry: string
  }
}

export const generatedRegistryItems = [
  {
    "name": "accordion",
    "type": "primitive",
    "title": "Accordion",
    "description": "Expandable content sections with smooth disclosure behavior.",
    "docsPath": "/docs/components/accordion",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add accordion"
    }
  },
  {
    "name": "alert",
    "type": "primitive",
    "title": "Alert",
    "description": "Contextual feedback message with default, glass, outline, and ghost variants.",
    "docsPath": "/docs/components/alert",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add alert"
    }
  },
  {
    "name": "alert-dialog",
    "type": "primitive",
    "title": "Alert Dialog",
    "description": "Destructive action confirmation dialog with explicit cancel and action controls.",
    "docsPath": "/docs/components/alert-dialog",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add alert-dialog"
    }
  },
  {
    "name": "animated-gradient",
    "type": "signature",
    "title": "Animated Gradient",
    "description": "Animated color-shifting gradient background with warm, cool, aurora, and glass presets.",
    "docsPath": "/docs/components/animated-gradient",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add animated-gradient"
    }
  },
  {
    "name": "aurora-background",
    "type": "signature",
    "title": "Aurora Background",
    "description": "Animated gradient mesh backdrop with floating blurred blobs.",
    "docsPath": "/docs/components/aurora-background",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add aurora-background"
    }
  },
  {
    "name": "avatar",
    "type": "primitive",
    "title": "Avatar",
    "description": "Profile image with SVG-ready sources, fallback rendering, and multiple glass-aware surface variants.",
    "docsPath": "/docs/components/avatar",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add avatar"
    }
  },
  {
    "name": "badge",
    "type": "primitive",
    "title": "Badge",
    "description": "Compact status indicator for labels, states, and counts.",
    "docsPath": "/docs/components/badge",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add badge"
    }
  },
  {
    "name": "blur-fade",
    "type": "signature",
    "title": "Blur Fade",
    "description": "Scroll-triggered entrance animation with blur, fade, and slide transitions.",
    "docsPath": "/docs/components/blur-fade",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add blur-fade"
    }
  },
  {
    "name": "blur-spotlight",
    "type": "signature",
    "title": "Blur Spotlight",
    "description": "Cursor-following ambient glow effect for background layers.",
    "docsPath": "/docs/components/blur-spotlight",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add blur-spotlight"
    }
  },
  {
    "name": "border-beam",
    "type": "signature",
    "title": "Border Beam",
    "description": "Light beam that travels along the border of its container via CSS offset-path.",
    "docsPath": "/docs/components/border-beam",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add border-beam"
    }
  },
  {
    "name": "button",
    "type": "primitive",
    "title": "Button",
    "description": "Action control with default, glass, liquid, matte, glow, outline, and ghost variants.",
    "docsPath": "/docs/components/button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add button"
    }
  },
  {
    "name": "card",
    "type": "primitive",
    "title": "Card",
    "description": "Flexible surface container for grouped content.",
    "docsPath": "/docs/components/card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add card"
    }
  },
  {
    "name": "checkbox",
    "type": "primitive",
    "title": "Checkbox",
    "description": "Radix checkbox with glass, liquid, matte, and outline surface variants.",
    "docsPath": "/docs/components/checkbox",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add checkbox"
    }
  },
  {
    "name": "chip",
    "type": "primitive",
    "title": "Chip",
    "description": "Compact pill-style tag for statuses and lightweight metadata.",
    "docsPath": "/docs/components/chip",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add chip"
    }
  },
  {
    "name": "chromatic-text",
    "type": "signature",
    "title": "Chromatic Text",
    "description": "Text with chromatic aberration effect — RGB channel splitting.",
    "docsPath": "/docs/components/chromatic-text",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add chromatic-text"
    }
  },
  {
    "name": "code",
    "type": "primitive",
    "title": "Code",
    "description": "Inline code element for commands, snippets, and tokenized literals.",
    "docsPath": "/docs/components/code",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add code"
    }
  },
  {
    "name": "command",
    "type": "primitive",
    "title": "Command",
    "description": "Command palette for keyboard-driven actions and search.",
    "docsPath": "/docs/components/command",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add command"
    }
  },
  {
    "name": "counter",
    "type": "primitive",
    "title": "Counter",
    "description": "Numeric badge that compacts overflow values like 99+.",
    "docsPath": "/docs/components/counter",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add counter"
    }
  },
  {
    "name": "data-table",
    "type": "primitive",
    "title": "Data Table",
    "description": "Feature-rich table wrapper with search, sorting, pagination, selection, and column controls.",
    "docsPath": "/docs/components/data-table",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add data-table"
    }
  },
  {
    "name": "depth-card",
    "type": "signature",
    "title": "Depth Card",
    "description": "Parallax tilt card with layered glass planes and glare effect on hover.",
    "docsPath": "/docs/components/depth-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add depth-card"
    }
  },
  {
    "name": "dot-pattern",
    "type": "signature",
    "title": "Dot Pattern",
    "description": "Static SVG dot grid background with configurable size, gap, and theme colors.",
    "docsPath": "/docs/components/dot-pattern",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add dot-pattern"
    }
  },
  {
    "name": "dropdown-menu",
    "type": "primitive",
    "title": "Dropdown Menu",
    "description": "Action menu anchored to a trigger with keyboard navigation.",
    "docsPath": "/docs/components/dropdown-menu",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add dropdown-menu"
    }
  },
  {
    "name": "floating-panel",
    "type": "signature",
    "title": "Floating Panel",
    "description": "Draggable glass panel with depth shadows and optional close button.",
    "docsPath": "/docs/components/floating-panel",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add floating-panel"
    }
  },
  {
    "name": "glass-breadcrumb",
    "type": "signature",
    "title": "Glass Breadcrumb",
    "description": "Pill-style breadcrumb with glass indicators and collapsible items.",
    "docsPath": "/docs/components/glass-breadcrumb",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-breadcrumb"
    }
  },
  {
    "name": "glass-card",
    "type": "signature",
    "title": "Glass Card",
    "description": "Frosted card with depth-aware blur, refraction edge highlights, and elevation transitions.",
    "docsPath": "/docs/components/glass-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-card"
    }
  },
  {
    "name": "glass-dock",
    "type": "signature",
    "title": "Glass Dock",
    "description": "macOS-style dock with proximity magnification and frosted glass surface.",
    "docsPath": "/docs/components/glass-dock",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-dock"
    }
  },
  {
    "name": "glass-navbar",
    "type": "signature",
    "title": "Glass Navbar",
    "description": "Translucent navigation bar that responds to scroll with blur intensity.",
    "docsPath": "/docs/components/glass-navbar",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-navbar"
    }
  },
  {
    "name": "glass-toggle",
    "type": "signature",
    "title": "Glass Toggle",
    "description": "Toggle switch with liquid fill animation and frosted glass surface.",
    "docsPath": "/docs/components/glass-toggle",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-toggle"
    }
  },
  {
    "name": "glow-border",
    "type": "signature",
    "title": "Glow Border",
    "description": "Rotating conic-gradient glow effect around container border.",
    "docsPath": "/docs/components/glow-border",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glow-border"
    }
  },
  {
    "name": "gradient-mesh",
    "type": "signature",
    "title": "Gradient Mesh",
    "description": "Generative mesh gradient background using overlapping radial gradients.",
    "docsPath": "/docs/components/gradient-mesh",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add gradient-mesh"
    }
  },
  {
    "name": "heading",
    "type": "primitive",
    "title": "Heading",
    "description": "Semantic heading primitive with independent style scaling.",
    "docsPath": "/docs/components/heading",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add heading"
    }
  },
  {
    "name": "hover-card",
    "type": "primitive",
    "title": "Hover Card",
    "description": "Preview card that appears on hover or focus with configurable delays and placement.",
    "docsPath": "/docs/components/hover-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add hover-card"
    }
  },
  {
    "name": "icon-frame",
    "type": "primitive",
    "title": "Icon Frame",
    "description": "Consistent framed surface for icon glyphs and short initials.",
    "docsPath": "/docs/components/icon-frame",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add icon-frame"
    }
  },
  {
    "name": "input",
    "type": "primitive",
    "title": "Input",
    "description": "Single-line input with glass, liquid, matte, and utility variants.",
    "docsPath": "/docs/components/input",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add input"
    }
  },
  {
    "name": "kbd",
    "type": "primitive",
    "title": "Kbd",
    "description": "Keyboard keycap primitive for shortcuts and key hints.",
    "docsPath": "/docs/components/kbd",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add kbd"
    }
  },
  {
    "name": "label",
    "type": "primitive",
    "title": "Label",
    "description": "Form label primitive with shared glass-aware variants.",
    "docsPath": "/docs/components/label",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add label"
    }
  },
  {
    "name": "light-leak",
    "type": "signature",
    "title": "Light Leak",
    "description": "Simulated lens flare and light leak overlay with drifting animation.",
    "docsPath": "/docs/components/light-leak",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add light-leak"
    }
  },
  {
    "name": "link",
    "type": "primitive",
    "title": "Link",
    "description": "Tokenized anchor primitive with focus ring and variant surfaces.",
    "docsPath": "/docs/components/link",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add link"
    }
  },
  {
    "name": "liquid-button",
    "type": "signature",
    "title": "Liquid Button",
    "description": "Button with fluid hover lift, press squish, and radial shine effect.",
    "docsPath": "/docs/components/liquid-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add liquid-button"
    }
  },
  {
    "name": "magnetic-cta",
    "type": "signature",
    "title": "Magnetic CTA",
    "description": "Call-to-action button with subtle cursor-attraction on hover.",
    "docsPath": "/docs/components/magnetic-cta",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add magnetic-cta"
    }
  },
  {
    "name": "marquee",
    "type": "signature",
    "title": "Marquee",
    "description": "Infinite horizontal or vertical scrolling content with pause-on-hover support.",
    "docsPath": "/docs/components/marquee",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add marquee"
    }
  },
  {
    "name": "meteor-shower",
    "type": "signature",
    "title": "Meteor Shower",
    "description": "Falling diagonal streaks with staggered delays for hero backgrounds.",
    "docsPath": "/docs/components/meteor-shower",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add meteor-shower"
    }
  },
  {
    "name": "modal",
    "type": "primitive",
    "title": "Modal / Dialog",
    "description": "Layered dialog for focused tasks or confirmations.",
    "docsPath": "/docs/components/modal",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add modal"
    }
  },
  {
    "name": "morphing-tabs",
    "type": "signature",
    "title": "Morphing Tabs",
    "description": "Tab component with a smoothly sliding indicator that morphs between items.",
    "docsPath": "/docs/components/morphing-tabs",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add morphing-tabs"
    }
  },
  {
    "name": "number-ticker",
    "type": "signature",
    "title": "Number Ticker",
    "description": "Animated number counter triggered by scroll visibility via IntersectionObserver.",
    "docsPath": "/docs/components/number-ticker",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add number-ticker"
    }
  },
  {
    "name": "orbiting-circles",
    "type": "signature",
    "title": "Orbiting Circles",
    "description": "CSS-driven orbital animation that keeps children upright via double-rotate.",
    "docsPath": "/docs/components/orbiting-circles",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add orbiting-circles"
    }
  },
  {
    "name": "particle-field",
    "type": "signature",
    "title": "Particle Field",
    "description": "Ambient floating particle system with CSS-only staggered animations.",
    "docsPath": "/docs/components/particle-field",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add particle-field"
    }
  },
  {
    "name": "popover",
    "type": "primitive",
    "title": "Popover",
    "description": "Floating content panel anchored to a trigger element.",
    "docsPath": "/docs/components/popover",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add popover"
    }
  },
  {
    "name": "prism-border",
    "type": "signature",
    "title": "Prism Border",
    "description": "Animated rainbow refraction border using a shifting linear gradient.",
    "docsPath": "/docs/components/prism-border",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add prism-border"
    }
  },
  {
    "name": "progress",
    "type": "primitive",
    "title": "Progress",
    "description": "Determinate linear and circular progress indicators with tokenized variants and sizing.",
    "docsPath": "/docs/components/progress",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add progress"
    }
  },
  {
    "name": "pulsating-button",
    "type": "signature",
    "title": "Pulsating Button",
    "description": "Button with a pulsing glow ring animation for attention-grabbing CTAs.",
    "docsPath": "/docs/components/pulsating-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add pulsating-button"
    }
  },
  {
    "name": "radio-group",
    "type": "primitive",
    "title": "Radio Group",
    "description": "Mutually exclusive selection control with variant-capable radio items.",
    "docsPath": "/docs/components/radio-group",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add radio-group"
    }
  },
  {
    "name": "retro-grid",
    "type": "signature",
    "title": "Retro Grid",
    "description": "CSS perspective grid with scrolling lines for retro-futuristic backgrounds.",
    "docsPath": "/docs/components/retro-grid",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add retro-grid"
    }
  },
  {
    "name": "reveal-text",
    "type": "signature",
    "title": "Reveal Text",
    "description": "Text that reveals through a clip-path wipe animation triggered on view.",
    "docsPath": "/docs/components/reveal-text",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add reveal-text"
    }
  },
  {
    "name": "ripple",
    "type": "signature",
    "title": "Ripple",
    "description": "Concentric expanding rings radiating from center for decorative backgrounds.",
    "docsPath": "/docs/components/ripple",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add ripple"
    }
  },
  {
    "name": "ripple-button",
    "type": "signature",
    "title": "Ripple Button",
    "description": "Button with liquid ripple effect on press.",
    "docsPath": "/docs/components/ripple-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add ripple-button"
    }
  },
  {
    "name": "select",
    "type": "primitive",
    "title": "Select",
    "description": "Native select with glass, liquid, matte, and utility variants.",
    "docsPath": "/docs/components/select",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add select"
    }
  },
  {
    "name": "separator",
    "type": "primitive",
    "title": "Separator",
    "description": "Visual divider for grouping content with orientation support.",
    "docsPath": "/docs/components/separator",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add separator"
    }
  },
  {
    "name": "sheet",
    "type": "primitive",
    "title": "Sheet / Drawer",
    "description": "Sliding panel for side, top, or bottom contextual workflows.",
    "docsPath": "/docs/components/sheet",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add sheet"
    }
  },
  {
    "name": "shimmer-button",
    "type": "signature",
    "title": "Shimmer Button",
    "description": "Button with animated shimmer sweep overlay and glass-aware variants.",
    "docsPath": "/docs/components/shimmer-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add shimmer-button"
    }
  },
  {
    "name": "skeleton",
    "type": "primitive",
    "title": "Skeleton",
    "description": "Loading placeholder surface with reduced-motion fallback.",
    "docsPath": "/docs/components/skeleton",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add skeleton"
    }
  },
  {
    "name": "slider",
    "type": "primitive",
    "title": "Slider",
    "description": "Range input control built on Radix slider primitive with glass thumb/track styling.",
    "docsPath": "/docs/components/slider",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add slider"
    }
  },
  {
    "name": "spotlight",
    "type": "signature",
    "title": "Spotlight",
    "description": "Full-page spotlight overlay for onboarding and feature highlighting.",
    "docsPath": "/docs/components/spotlight",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add spotlight"
    }
  },
  {
    "name": "spotlight-card",
    "type": "signature",
    "title": "Spotlight Card",
    "description": "Card with cursor-tracked radial spotlight effect on hover.",
    "docsPath": "/docs/components/spotlight-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add spotlight-card"
    }
  },
  {
    "name": "status-dot",
    "type": "primitive",
    "title": "Status Dot",
    "description": "Colored status indicator with optional label and pulse state.",
    "docsPath": "/docs/components/status-dot",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add status-dot"
    }
  },
  {
    "name": "switch",
    "type": "primitive",
    "title": "Switch",
    "description": "On/off control built on Radix switch primitive.",
    "docsPath": "/docs/components/switch",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add switch"
    }
  },
  {
    "name": "table",
    "type": "primitive",
    "title": "Table",
    "description": "Composable data table with semantic sections and glass variant support.",
    "docsPath": "/docs/components/table",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add table"
    }
  },
  {
    "name": "tabs",
    "type": "primitive",
    "title": "Tabs",
    "description": "Tabbed interface for switching between grouped content panels.",
    "docsPath": "/docs/components/tabs",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add tabs"
    }
  },
  {
    "name": "text",
    "type": "primitive",
    "title": "Text",
    "description": "Body text primitive for default, muted, and glass-highlighted copy.",
    "docsPath": "/docs/components/text",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add text"
    }
  },
  {
    "name": "text-reveal",
    "type": "signature",
    "title": "Text Reveal",
    "description": "Word-by-word opacity reveal driven by scroll position.",
    "docsPath": "/docs/components/text-reveal",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add text-reveal"
    }
  },
  {
    "name": "textarea",
    "type": "primitive",
    "title": "Textarea",
    "description": "Multi-line input with glass, liquid, matte, and utility variants.",
    "docsPath": "/docs/components/textarea",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add textarea"
    }
  },
  {
    "name": "toast",
    "type": "primitive",
    "title": "Toast",
    "description": "Glassmorphic toast notifications powered by Sonner with success, error, warning, info, loading, promise, and action support.",
    "docsPath": "/docs/components/toast",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add toast"
    }
  },
  {
    "name": "tooltip",
    "type": "primitive",
    "title": "Tooltip",
    "description": "Context hint on hover/focus using Radix tooltip primitive.",
    "docsPath": "/docs/components/tooltip",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add tooltip"
    }
  },
  {
    "name": "tree",
    "type": "primitive",
    "title": "Tree",
    "description": "Hierarchical tree view for file structures, navigation, and nested data.",
    "docsPath": "/docs/components/tree",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add tree"
    }
  },
  {
    "name": "typewriter",
    "type": "signature",
    "title": "Typewriter",
    "description": "Character-by-character typing animation with blinking cursor and loop support.",
    "docsPath": "/docs/components/typewriter",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add typewriter"
    }
  },
  {
    "name": "word-rotate",
    "type": "signature",
    "title": "Word Rotate",
    "description": "Cycling text animation that rotates through an array of words.",
    "docsPath": "/docs/components/word-rotate",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add word-rotate"
    }
  }
] as const
export const generatedRegistryByName = {
  "accordion": {
    "name": "accordion",
    "type": "primitive",
    "title": "Accordion",
    "description": "Expandable content sections with smooth disclosure behavior.",
    "docsPath": "/docs/components/accordion",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add accordion"
    }
  },
  "alert": {
    "name": "alert",
    "type": "primitive",
    "title": "Alert",
    "description": "Contextual feedback message with default, glass, outline, and ghost variants.",
    "docsPath": "/docs/components/alert",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add alert"
    }
  },
  "alert-dialog": {
    "name": "alert-dialog",
    "type": "primitive",
    "title": "Alert Dialog",
    "description": "Destructive action confirmation dialog with explicit cancel and action controls.",
    "docsPath": "/docs/components/alert-dialog",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add alert-dialog"
    }
  },
  "animated-gradient": {
    "name": "animated-gradient",
    "type": "signature",
    "title": "Animated Gradient",
    "description": "Animated color-shifting gradient background with warm, cool, aurora, and glass presets.",
    "docsPath": "/docs/components/animated-gradient",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add animated-gradient"
    }
  },
  "aurora-background": {
    "name": "aurora-background",
    "type": "signature",
    "title": "Aurora Background",
    "description": "Animated gradient mesh backdrop with floating blurred blobs.",
    "docsPath": "/docs/components/aurora-background",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add aurora-background"
    }
  },
  "avatar": {
    "name": "avatar",
    "type": "primitive",
    "title": "Avatar",
    "description": "Profile image with SVG-ready sources, fallback rendering, and multiple glass-aware surface variants.",
    "docsPath": "/docs/components/avatar",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add avatar"
    }
  },
  "badge": {
    "name": "badge",
    "type": "primitive",
    "title": "Badge",
    "description": "Compact status indicator for labels, states, and counts.",
    "docsPath": "/docs/components/badge",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add badge"
    }
  },
  "blur-fade": {
    "name": "blur-fade",
    "type": "signature",
    "title": "Blur Fade",
    "description": "Scroll-triggered entrance animation with blur, fade, and slide transitions.",
    "docsPath": "/docs/components/blur-fade",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add blur-fade"
    }
  },
  "blur-spotlight": {
    "name": "blur-spotlight",
    "type": "signature",
    "title": "Blur Spotlight",
    "description": "Cursor-following ambient glow effect for background layers.",
    "docsPath": "/docs/components/blur-spotlight",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add blur-spotlight"
    }
  },
  "border-beam": {
    "name": "border-beam",
    "type": "signature",
    "title": "Border Beam",
    "description": "Light beam that travels along the border of its container via CSS offset-path.",
    "docsPath": "/docs/components/border-beam",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add border-beam"
    }
  },
  "button": {
    "name": "button",
    "type": "primitive",
    "title": "Button",
    "description": "Action control with default, glass, liquid, matte, glow, outline, and ghost variants.",
    "docsPath": "/docs/components/button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add button"
    }
  },
  "card": {
    "name": "card",
    "type": "primitive",
    "title": "Card",
    "description": "Flexible surface container for grouped content.",
    "docsPath": "/docs/components/card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add card"
    }
  },
  "checkbox": {
    "name": "checkbox",
    "type": "primitive",
    "title": "Checkbox",
    "description": "Radix checkbox with glass, liquid, matte, and outline surface variants.",
    "docsPath": "/docs/components/checkbox",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add checkbox"
    }
  },
  "chip": {
    "name": "chip",
    "type": "primitive",
    "title": "Chip",
    "description": "Compact pill-style tag for statuses and lightweight metadata.",
    "docsPath": "/docs/components/chip",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add chip"
    }
  },
  "chromatic-text": {
    "name": "chromatic-text",
    "type": "signature",
    "title": "Chromatic Text",
    "description": "Text with chromatic aberration effect — RGB channel splitting.",
    "docsPath": "/docs/components/chromatic-text",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add chromatic-text"
    }
  },
  "code": {
    "name": "code",
    "type": "primitive",
    "title": "Code",
    "description": "Inline code element for commands, snippets, and tokenized literals.",
    "docsPath": "/docs/components/code",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add code"
    }
  },
  "command": {
    "name": "command",
    "type": "primitive",
    "title": "Command",
    "description": "Command palette for keyboard-driven actions and search.",
    "docsPath": "/docs/components/command",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add command"
    }
  },
  "counter": {
    "name": "counter",
    "type": "primitive",
    "title": "Counter",
    "description": "Numeric badge that compacts overflow values like 99+.",
    "docsPath": "/docs/components/counter",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add counter"
    }
  },
  "data-table": {
    "name": "data-table",
    "type": "primitive",
    "title": "Data Table",
    "description": "Feature-rich table wrapper with search, sorting, pagination, selection, and column controls.",
    "docsPath": "/docs/components/data-table",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add data-table"
    }
  },
  "depth-card": {
    "name": "depth-card",
    "type": "signature",
    "title": "Depth Card",
    "description": "Parallax tilt card with layered glass planes and glare effect on hover.",
    "docsPath": "/docs/components/depth-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add depth-card"
    }
  },
  "dot-pattern": {
    "name": "dot-pattern",
    "type": "signature",
    "title": "Dot Pattern",
    "description": "Static SVG dot grid background with configurable size, gap, and theme colors.",
    "docsPath": "/docs/components/dot-pattern",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add dot-pattern"
    }
  },
  "dropdown-menu": {
    "name": "dropdown-menu",
    "type": "primitive",
    "title": "Dropdown Menu",
    "description": "Action menu anchored to a trigger with keyboard navigation.",
    "docsPath": "/docs/components/dropdown-menu",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add dropdown-menu"
    }
  },
  "floating-panel": {
    "name": "floating-panel",
    "type": "signature",
    "title": "Floating Panel",
    "description": "Draggable glass panel with depth shadows and optional close button.",
    "docsPath": "/docs/components/floating-panel",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add floating-panel"
    }
  },
  "glass-breadcrumb": {
    "name": "glass-breadcrumb",
    "type": "signature",
    "title": "Glass Breadcrumb",
    "description": "Pill-style breadcrumb with glass indicators and collapsible items.",
    "docsPath": "/docs/components/glass-breadcrumb",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-breadcrumb"
    }
  },
  "glass-card": {
    "name": "glass-card",
    "type": "signature",
    "title": "Glass Card",
    "description": "Frosted card with depth-aware blur, refraction edge highlights, and elevation transitions.",
    "docsPath": "/docs/components/glass-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-card"
    }
  },
  "glass-dock": {
    "name": "glass-dock",
    "type": "signature",
    "title": "Glass Dock",
    "description": "macOS-style dock with proximity magnification and frosted glass surface.",
    "docsPath": "/docs/components/glass-dock",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-dock"
    }
  },
  "glass-navbar": {
    "name": "glass-navbar",
    "type": "signature",
    "title": "Glass Navbar",
    "description": "Translucent navigation bar that responds to scroll with blur intensity.",
    "docsPath": "/docs/components/glass-navbar",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-navbar"
    }
  },
  "glass-toggle": {
    "name": "glass-toggle",
    "type": "signature",
    "title": "Glass Toggle",
    "description": "Toggle switch with liquid fill animation and frosted glass surface.",
    "docsPath": "/docs/components/glass-toggle",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glass-toggle"
    }
  },
  "glow-border": {
    "name": "glow-border",
    "type": "signature",
    "title": "Glow Border",
    "description": "Rotating conic-gradient glow effect around container border.",
    "docsPath": "/docs/components/glow-border",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add glow-border"
    }
  },
  "gradient-mesh": {
    "name": "gradient-mesh",
    "type": "signature",
    "title": "Gradient Mesh",
    "description": "Generative mesh gradient background using overlapping radial gradients.",
    "docsPath": "/docs/components/gradient-mesh",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add gradient-mesh"
    }
  },
  "heading": {
    "name": "heading",
    "type": "primitive",
    "title": "Heading",
    "description": "Semantic heading primitive with independent style scaling.",
    "docsPath": "/docs/components/heading",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add heading"
    }
  },
  "hover-card": {
    "name": "hover-card",
    "type": "primitive",
    "title": "Hover Card",
    "description": "Preview card that appears on hover or focus with configurable delays and placement.",
    "docsPath": "/docs/components/hover-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add hover-card"
    }
  },
  "icon-frame": {
    "name": "icon-frame",
    "type": "primitive",
    "title": "Icon Frame",
    "description": "Consistent framed surface for icon glyphs and short initials.",
    "docsPath": "/docs/components/icon-frame",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add icon-frame"
    }
  },
  "input": {
    "name": "input",
    "type": "primitive",
    "title": "Input",
    "description": "Single-line input with glass, liquid, matte, and utility variants.",
    "docsPath": "/docs/components/input",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add input"
    }
  },
  "kbd": {
    "name": "kbd",
    "type": "primitive",
    "title": "Kbd",
    "description": "Keyboard keycap primitive for shortcuts and key hints.",
    "docsPath": "/docs/components/kbd",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add kbd"
    }
  },
  "label": {
    "name": "label",
    "type": "primitive",
    "title": "Label",
    "description": "Form label primitive with shared glass-aware variants.",
    "docsPath": "/docs/components/label",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add label"
    }
  },
  "light-leak": {
    "name": "light-leak",
    "type": "signature",
    "title": "Light Leak",
    "description": "Simulated lens flare and light leak overlay with drifting animation.",
    "docsPath": "/docs/components/light-leak",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add light-leak"
    }
  },
  "link": {
    "name": "link",
    "type": "primitive",
    "title": "Link",
    "description": "Tokenized anchor primitive with focus ring and variant surfaces.",
    "docsPath": "/docs/components/link",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add link"
    }
  },
  "liquid-button": {
    "name": "liquid-button",
    "type": "signature",
    "title": "Liquid Button",
    "description": "Button with fluid hover lift, press squish, and radial shine effect.",
    "docsPath": "/docs/components/liquid-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add liquid-button"
    }
  },
  "magnetic-cta": {
    "name": "magnetic-cta",
    "type": "signature",
    "title": "Magnetic CTA",
    "description": "Call-to-action button with subtle cursor-attraction on hover.",
    "docsPath": "/docs/components/magnetic-cta",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add magnetic-cta"
    }
  },
  "marquee": {
    "name": "marquee",
    "type": "signature",
    "title": "Marquee",
    "description": "Infinite horizontal or vertical scrolling content with pause-on-hover support.",
    "docsPath": "/docs/components/marquee",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add marquee"
    }
  },
  "meteor-shower": {
    "name": "meteor-shower",
    "type": "signature",
    "title": "Meteor Shower",
    "description": "Falling diagonal streaks with staggered delays for hero backgrounds.",
    "docsPath": "/docs/components/meteor-shower",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add meteor-shower"
    }
  },
  "modal": {
    "name": "modal",
    "type": "primitive",
    "title": "Modal / Dialog",
    "description": "Layered dialog for focused tasks or confirmations.",
    "docsPath": "/docs/components/modal",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add modal"
    }
  },
  "morphing-tabs": {
    "name": "morphing-tabs",
    "type": "signature",
    "title": "Morphing Tabs",
    "description": "Tab component with a smoothly sliding indicator that morphs between items.",
    "docsPath": "/docs/components/morphing-tabs",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add morphing-tabs"
    }
  },
  "number-ticker": {
    "name": "number-ticker",
    "type": "signature",
    "title": "Number Ticker",
    "description": "Animated number counter triggered by scroll visibility via IntersectionObserver.",
    "docsPath": "/docs/components/number-ticker",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add number-ticker"
    }
  },
  "orbiting-circles": {
    "name": "orbiting-circles",
    "type": "signature",
    "title": "Orbiting Circles",
    "description": "CSS-driven orbital animation that keeps children upright via double-rotate.",
    "docsPath": "/docs/components/orbiting-circles",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add orbiting-circles"
    }
  },
  "particle-field": {
    "name": "particle-field",
    "type": "signature",
    "title": "Particle Field",
    "description": "Ambient floating particle system with CSS-only staggered animations.",
    "docsPath": "/docs/components/particle-field",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add particle-field"
    }
  },
  "popover": {
    "name": "popover",
    "type": "primitive",
    "title": "Popover",
    "description": "Floating content panel anchored to a trigger element.",
    "docsPath": "/docs/components/popover",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add popover"
    }
  },
  "prism-border": {
    "name": "prism-border",
    "type": "signature",
    "title": "Prism Border",
    "description": "Animated rainbow refraction border using a shifting linear gradient.",
    "docsPath": "/docs/components/prism-border",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add prism-border"
    }
  },
  "progress": {
    "name": "progress",
    "type": "primitive",
    "title": "Progress",
    "description": "Determinate linear and circular progress indicators with tokenized variants and sizing.",
    "docsPath": "/docs/components/progress",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add progress"
    }
  },
  "pulsating-button": {
    "name": "pulsating-button",
    "type": "signature",
    "title": "Pulsating Button",
    "description": "Button with a pulsing glow ring animation for attention-grabbing CTAs.",
    "docsPath": "/docs/components/pulsating-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add pulsating-button"
    }
  },
  "radio-group": {
    "name": "radio-group",
    "type": "primitive",
    "title": "Radio Group",
    "description": "Mutually exclusive selection control with variant-capable radio items.",
    "docsPath": "/docs/components/radio-group",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add radio-group"
    }
  },
  "retro-grid": {
    "name": "retro-grid",
    "type": "signature",
    "title": "Retro Grid",
    "description": "CSS perspective grid with scrolling lines for retro-futuristic backgrounds.",
    "docsPath": "/docs/components/retro-grid",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add retro-grid"
    }
  },
  "reveal-text": {
    "name": "reveal-text",
    "type": "signature",
    "title": "Reveal Text",
    "description": "Text that reveals through a clip-path wipe animation triggered on view.",
    "docsPath": "/docs/components/reveal-text",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add reveal-text"
    }
  },
  "ripple": {
    "name": "ripple",
    "type": "signature",
    "title": "Ripple",
    "description": "Concentric expanding rings radiating from center for decorative backgrounds.",
    "docsPath": "/docs/components/ripple",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add ripple"
    }
  },
  "ripple-button": {
    "name": "ripple-button",
    "type": "signature",
    "title": "Ripple Button",
    "description": "Button with liquid ripple effect on press.",
    "docsPath": "/docs/components/ripple-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add ripple-button"
    }
  },
  "select": {
    "name": "select",
    "type": "primitive",
    "title": "Select",
    "description": "Native select with glass, liquid, matte, and utility variants.",
    "docsPath": "/docs/components/select",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add select"
    }
  },
  "separator": {
    "name": "separator",
    "type": "primitive",
    "title": "Separator",
    "description": "Visual divider for grouping content with orientation support.",
    "docsPath": "/docs/components/separator",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add separator"
    }
  },
  "sheet": {
    "name": "sheet",
    "type": "primitive",
    "title": "Sheet / Drawer",
    "description": "Sliding panel for side, top, or bottom contextual workflows.",
    "docsPath": "/docs/components/sheet",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add sheet"
    }
  },
  "shimmer-button": {
    "name": "shimmer-button",
    "type": "signature",
    "title": "Shimmer Button",
    "description": "Button with animated shimmer sweep overlay and glass-aware variants.",
    "docsPath": "/docs/components/shimmer-button",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add shimmer-button"
    }
  },
  "skeleton": {
    "name": "skeleton",
    "type": "primitive",
    "title": "Skeleton",
    "description": "Loading placeholder surface with reduced-motion fallback.",
    "docsPath": "/docs/components/skeleton",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add skeleton"
    }
  },
  "slider": {
    "name": "slider",
    "type": "primitive",
    "title": "Slider",
    "description": "Range input control built on Radix slider primitive with glass thumb/track styling.",
    "docsPath": "/docs/components/slider",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add slider"
    }
  },
  "spotlight": {
    "name": "spotlight",
    "type": "signature",
    "title": "Spotlight",
    "description": "Full-page spotlight overlay for onboarding and feature highlighting.",
    "docsPath": "/docs/components/spotlight",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add spotlight"
    }
  },
  "spotlight-card": {
    "name": "spotlight-card",
    "type": "signature",
    "title": "Spotlight Card",
    "description": "Card with cursor-tracked radial spotlight effect on hover.",
    "docsPath": "/docs/components/spotlight-card",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add spotlight-card"
    }
  },
  "status-dot": {
    "name": "status-dot",
    "type": "primitive",
    "title": "Status Dot",
    "description": "Colored status indicator with optional label and pulse state.",
    "docsPath": "/docs/components/status-dot",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add status-dot"
    }
  },
  "switch": {
    "name": "switch",
    "type": "primitive",
    "title": "Switch",
    "description": "On/off control built on Radix switch primitive.",
    "docsPath": "/docs/components/switch",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add switch"
    }
  },
  "table": {
    "name": "table",
    "type": "primitive",
    "title": "Table",
    "description": "Composable data table with semantic sections and glass variant support.",
    "docsPath": "/docs/components/table",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add table"
    }
  },
  "tabs": {
    "name": "tabs",
    "type": "primitive",
    "title": "Tabs",
    "description": "Tabbed interface for switching between grouped content panels.",
    "docsPath": "/docs/components/tabs",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add tabs"
    }
  },
  "text": {
    "name": "text",
    "type": "primitive",
    "title": "Text",
    "description": "Body text primitive for default, muted, and glass-highlighted copy.",
    "docsPath": "/docs/components/text",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add text"
    }
  },
  "text-reveal": {
    "name": "text-reveal",
    "type": "signature",
    "title": "Text Reveal",
    "description": "Word-by-word opacity reveal driven by scroll position.",
    "docsPath": "/docs/components/text-reveal",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add text-reveal"
    }
  },
  "textarea": {
    "name": "textarea",
    "type": "primitive",
    "title": "Textarea",
    "description": "Multi-line input with glass, liquid, matte, and utility variants.",
    "docsPath": "/docs/components/textarea",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add textarea"
    }
  },
  "toast": {
    "name": "toast",
    "type": "primitive",
    "title": "Toast",
    "description": "Glassmorphic toast notifications powered by Sonner with success, error, warning, info, loading, promise, and action support.",
    "docsPath": "/docs/components/toast",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add toast"
    }
  },
  "tooltip": {
    "name": "tooltip",
    "type": "primitive",
    "title": "Tooltip",
    "description": "Context hint on hover/focus using Radix tooltip primitive.",
    "docsPath": "/docs/components/tooltip",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add tooltip"
    }
  },
  "tree": {
    "name": "tree",
    "type": "primitive",
    "title": "Tree",
    "description": "Hierarchical tree view for file structures, navigation, and nested data.",
    "docsPath": "/docs/components/tree",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add tree"
    }
  },
  "typewriter": {
    "name": "typewriter",
    "type": "signature",
    "title": "Typewriter",
    "description": "Character-by-character typing animation with blinking cursor and loop support.",
    "docsPath": "/docs/components/typewriter",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add typewriter"
    }
  },
  "word-rotate": {
    "name": "word-rotate",
    "type": "signature",
    "title": "Word Rotate",
    "description": "Cycling text animation that rotates through an array of words.",
    "docsPath": "/docs/components/word-rotate",
    "importPath": "@glinui/ui",
    "install": {
      "package": "npm install @glinui/ui @glinui/tokens",
      "registry": "pnpm dlx @glinui/cli@latest add word-rotate"
    }
  }
} as const
export const generatedPrimitiveComponentIds = [
  "accordion",
  "alert",
  "alert-dialog",
  "avatar",
  "badge",
  "button",
  "card",
  "checkbox",
  "chip",
  "code",
  "command",
  "counter",
  "data-table",
  "dropdown-menu",
  "heading",
  "hover-card",
  "icon-frame",
  "input",
  "kbd",
  "label",
  "link",
  "modal",
  "popover",
  "progress",
  "radio-group",
  "select",
  "separator",
  "sheet",
  "skeleton",
  "slider",
  "status-dot",
  "switch",
  "table",
  "tabs",
  "text",
  "textarea",
  "toast",
  "tooltip",
  "tree"
] as const
export const generatedSignatureComponentIds = [
  "animated-gradient",
  "aurora-background",
  "blur-fade",
  "blur-spotlight",
  "border-beam",
  "chromatic-text",
  "depth-card",
  "dot-pattern",
  "floating-panel",
  "glass-breadcrumb",
  "glass-card",
  "glass-dock",
  "glass-navbar",
  "glass-toggle",
  "glow-border",
  "gradient-mesh",
  "light-leak",
  "liquid-button",
  "magnetic-cta",
  "marquee",
  "meteor-shower",
  "morphing-tabs",
  "number-ticker",
  "orbiting-circles",
  "particle-field",
  "prism-border",
  "pulsating-button",
  "retro-grid",
  "reveal-text",
  "ripple",
  "ripple-button",
  "shimmer-button",
  "spotlight",
  "spotlight-card",
  "text-reveal",
  "typewriter",
  "word-rotate"
] as const
export const generatedComponentTitles = {
  "accordion": "Accordion",
  "alert": "Alert",
  "alert-dialog": "Alert Dialog",
  "animated-gradient": "Animated Gradient",
  "aurora-background": "Aurora Background",
  "avatar": "Avatar",
  "badge": "Badge",
  "blur-fade": "Blur Fade",
  "blur-spotlight": "Blur Spotlight",
  "border-beam": "Border Beam",
  "button": "Button",
  "card": "Card",
  "checkbox": "Checkbox",
  "chip": "Chip",
  "chromatic-text": "Chromatic Text",
  "code": "Code",
  "command": "Command",
  "counter": "Counter",
  "data-table": "Data Table",
  "depth-card": "Depth Card",
  "dot-pattern": "Dot Pattern",
  "dropdown-menu": "Dropdown Menu",
  "floating-panel": "Floating Panel",
  "glass-breadcrumb": "Glass Breadcrumb",
  "glass-card": "Glass Card",
  "glass-dock": "Glass Dock",
  "glass-navbar": "Glass Navbar",
  "glass-toggle": "Glass Toggle",
  "glow-border": "Glow Border",
  "gradient-mesh": "Gradient Mesh",
  "heading": "Heading",
  "hover-card": "Hover Card",
  "icon-frame": "Icon Frame",
  "input": "Input",
  "kbd": "Kbd",
  "label": "Label",
  "light-leak": "Light Leak",
  "link": "Link",
  "liquid-button": "Liquid Button",
  "magnetic-cta": "Magnetic CTA",
  "marquee": "Marquee",
  "meteor-shower": "Meteor Shower",
  "modal": "Modal / Dialog",
  "morphing-tabs": "Morphing Tabs",
  "number-ticker": "Number Ticker",
  "orbiting-circles": "Orbiting Circles",
  "particle-field": "Particle Field",
  "popover": "Popover",
  "prism-border": "Prism Border",
  "progress": "Progress",
  "pulsating-button": "Pulsating Button",
  "radio-group": "Radio Group",
  "retro-grid": "Retro Grid",
  "reveal-text": "Reveal Text",
  "ripple": "Ripple",
  "ripple-button": "Ripple Button",
  "select": "Select",
  "separator": "Separator",
  "sheet": "Sheet / Drawer",
  "shimmer-button": "Shimmer Button",
  "skeleton": "Skeleton",
  "slider": "Slider",
  "spotlight": "Spotlight",
  "spotlight-card": "Spotlight Card",
  "status-dot": "Status Dot",
  "switch": "Switch",
  "table": "Table",
  "tabs": "Tabs",
  "text": "Text",
  "text-reveal": "Text Reveal",
  "textarea": "Textarea",
  "toast": "Toast",
  "tooltip": "Tooltip",
  "tree": "Tree",
  "typewriter": "Typewriter",
  "word-rotate": "Word Rotate"
} as const
export const generatedComponentDescriptions = {
  "accordion": "Expandable content sections with smooth disclosure behavior.",
  "alert": "Contextual feedback message with default, glass, outline, and ghost variants.",
  "alert-dialog": "Destructive action confirmation dialog with explicit cancel and action controls.",
  "animated-gradient": "Animated color-shifting gradient background with warm, cool, aurora, and glass presets.",
  "aurora-background": "Animated gradient mesh backdrop with floating blurred blobs.",
  "avatar": "Profile image with SVG-ready sources, fallback rendering, and multiple glass-aware surface variants.",
  "badge": "Compact status indicator for labels, states, and counts.",
  "blur-fade": "Scroll-triggered entrance animation with blur, fade, and slide transitions.",
  "blur-spotlight": "Cursor-following ambient glow effect for background layers.",
  "border-beam": "Light beam that travels along the border of its container via CSS offset-path.",
  "button": "Action control with default, glass, liquid, matte, glow, outline, and ghost variants.",
  "card": "Flexible surface container for grouped content.",
  "checkbox": "Radix checkbox with glass, liquid, matte, and outline surface variants.",
  "chip": "Compact pill-style tag for statuses and lightweight metadata.",
  "chromatic-text": "Text with chromatic aberration effect — RGB channel splitting.",
  "code": "Inline code element for commands, snippets, and tokenized literals.",
  "command": "Command palette for keyboard-driven actions and search.",
  "counter": "Numeric badge that compacts overflow values like 99+.",
  "data-table": "Feature-rich table wrapper with search, sorting, pagination, selection, and column controls.",
  "depth-card": "Parallax tilt card with layered glass planes and glare effect on hover.",
  "dot-pattern": "Static SVG dot grid background with configurable size, gap, and theme colors.",
  "dropdown-menu": "Action menu anchored to a trigger with keyboard navigation.",
  "floating-panel": "Draggable glass panel with depth shadows and optional close button.",
  "glass-breadcrumb": "Pill-style breadcrumb with glass indicators and collapsible items.",
  "glass-card": "Frosted card with depth-aware blur, refraction edge highlights, and elevation transitions.",
  "glass-dock": "macOS-style dock with proximity magnification and frosted glass surface.",
  "glass-navbar": "Translucent navigation bar that responds to scroll with blur intensity.",
  "glass-toggle": "Toggle switch with liquid fill animation and frosted glass surface.",
  "glow-border": "Rotating conic-gradient glow effect around container border.",
  "gradient-mesh": "Generative mesh gradient background using overlapping radial gradients.",
  "heading": "Semantic heading primitive with independent style scaling.",
  "hover-card": "Preview card that appears on hover or focus with configurable delays and placement.",
  "icon-frame": "Consistent framed surface for icon glyphs and short initials.",
  "input": "Single-line input with glass, liquid, matte, and utility variants.",
  "kbd": "Keyboard keycap primitive for shortcuts and key hints.",
  "label": "Form label primitive with shared glass-aware variants.",
  "light-leak": "Simulated lens flare and light leak overlay with drifting animation.",
  "link": "Tokenized anchor primitive with focus ring and variant surfaces.",
  "liquid-button": "Button with fluid hover lift, press squish, and radial shine effect.",
  "magnetic-cta": "Call-to-action button with subtle cursor-attraction on hover.",
  "marquee": "Infinite horizontal or vertical scrolling content with pause-on-hover support.",
  "meteor-shower": "Falling diagonal streaks with staggered delays for hero backgrounds.",
  "modal": "Layered dialog for focused tasks or confirmations.",
  "morphing-tabs": "Tab component with a smoothly sliding indicator that morphs between items.",
  "number-ticker": "Animated number counter triggered by scroll visibility via IntersectionObserver.",
  "orbiting-circles": "CSS-driven orbital animation that keeps children upright via double-rotate.",
  "particle-field": "Ambient floating particle system with CSS-only staggered animations.",
  "popover": "Floating content panel anchored to a trigger element.",
  "prism-border": "Animated rainbow refraction border using a shifting linear gradient.",
  "progress": "Determinate linear and circular progress indicators with tokenized variants and sizing.",
  "pulsating-button": "Button with a pulsing glow ring animation for attention-grabbing CTAs.",
  "radio-group": "Mutually exclusive selection control with variant-capable radio items.",
  "retro-grid": "CSS perspective grid with scrolling lines for retro-futuristic backgrounds.",
  "reveal-text": "Text that reveals through a clip-path wipe animation triggered on view.",
  "ripple": "Concentric expanding rings radiating from center for decorative backgrounds.",
  "ripple-button": "Button with liquid ripple effect on press.",
  "select": "Native select with glass, liquid, matte, and utility variants.",
  "separator": "Visual divider for grouping content with orientation support.",
  "sheet": "Sliding panel for side, top, or bottom contextual workflows.",
  "shimmer-button": "Button with animated shimmer sweep overlay and glass-aware variants.",
  "skeleton": "Loading placeholder surface with reduced-motion fallback.",
  "slider": "Range input control built on Radix slider primitive with glass thumb/track styling.",
  "spotlight": "Full-page spotlight overlay for onboarding and feature highlighting.",
  "spotlight-card": "Card with cursor-tracked radial spotlight effect on hover.",
  "status-dot": "Colored status indicator with optional label and pulse state.",
  "switch": "On/off control built on Radix switch primitive.",
  "table": "Composable data table with semantic sections and glass variant support.",
  "tabs": "Tabbed interface for switching between grouped content panels.",
  "text": "Body text primitive for default, muted, and glass-highlighted copy.",
  "text-reveal": "Word-by-word opacity reveal driven by scroll position.",
  "textarea": "Multi-line input with glass, liquid, matte, and utility variants.",
  "toast": "Glassmorphic toast notifications powered by Sonner with success, error, warning, info, loading, promise, and action support.",
  "tooltip": "Context hint on hover/focus using Radix tooltip primitive.",
  "tree": "Hierarchical tree view for file structures, navigation, and nested data.",
  "typewriter": "Character-by-character typing animation with blinking cursor and loop support.",
  "word-rotate": "Cycling text animation that rotates through an array of words."
} as const
export const generatedRegistryMetadataGeneratedAt = "2026-02-19T17:42:39.146Z" as const
